# Generated by Django 5.2.7 on 2025-10-11 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='stock.store'),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishments', to='stock.store'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stock.store'),
        ),
        migrations.AddField(
            model_name='dailysale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='stock.store'),
        ),
    ]
