
version: "3.9"

services:
  web:
    build: .
    container_name: tahlilchiai_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=api.tahlilchi-ai.uz
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: tahlilchiai_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: tahlilchiai_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email qarshiyevnizomiddin75@gmail.com
      --agree-tos
      --no-eff-email
      -d api.tahlilchi-ai.uz"

  db:
    image: postgres:16
    container_name: tahlilchiai_db
    environment:
      POSTGRES_DB: tahlilchi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  static_volume:
  media_volume:
  postgres_data:

